pages:
  image: griefed/gitlab-ci-cd:1.0.1
  stage: deploy
  script:
    - npm ci
    - npm run build
    - mv public public-vue
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - master
